spring.application.name=baleshop
spring.datasource.url=jdbc:mysql://localhost:3306/bale_shop
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
CLOUDINARY_NAME=dame7a9rv
CLOUDINARY_KEY=267827217416528
CLOUDINARY_SECRET=uA7CtSuciHpwW-VllhzLyT5sdfA